Repository newrelic/entity-definitions, pull requests merged in 2021-04, with the labels that each got.

#151 adding dashboard
  definitions/ext-network_synth/dashboard.json
  definitions/ext-network_synth/definition.yml
Labels: unsupported

#146 Entity synthesis for RF scanner device
  definitions/ext-rf_scanner/definition.yml
  definitions/ext-rf_scanner/golden_metrics.yml
  definitions/ext-rf_scanner/summary_metrics.yml
Labels: waiting on submitter feedback

#167 Added summary and golden metrics for multiple open instrumentation providers (ext-service)
  definitions/ext-service/definition.yml
  definitions/ext-service/golden_metrics.yml
  definitions/ext-service/summary_metrics.yml
Labels: question
