Repository newrelic/entity-definitions, pull requests merged in 2023-09, with the labels that each got.

#1222 [NR-143858] rename MetricRaw to Metric everywhere
  entity-types/ext-access_point/definition.yml
  entity-types/ext-access_point/tests/Metric.json
  entity-types/ext-otelcol/tests/Metric.json
  entity-types/ext-pixie_amqp/tests/Metric.json
  entity-types/ext-pixie_cassandra/tests/Metric.json
  entity-types/ext-pixie_dns/tests/Metric.json
  entity-types/ext-pixie_kafkabroker/tests/Metric.json
  entity-types/ext-pixie_mysql/tests/Metric.json
  entity-types/ext-pixie_postgres/tests/Metric.json
  entity-types/ext-pixie_redis/tests/Metric.json
  entity-types/ext-sap_hana/tests/Metric.json
  entity-types/ext-sap_oracle/tests/Metric.json
  entity-types/infra-azurefunctionsapp/tests/Metric.json
  entity-types/infra-azurewebapp/tests/Metric.json
  entity-types/infra-container/definition.yml
  entity-types/infra-host/definition.yml
  entity-types/infra-host/tests/Metric.json
  entity-types/infra-ibmmq_manager/definition.yml
  entity-types/infra-ibmmq_manager/tests/Metric.json
  entity-types/infra-ibmmq_queue/definition.yml
  entity-types/infra-ibmmq_queue/tests/Metric.json
  entity-types/infra-mongodb_collection/definition.yml
  entity-types/infra-mongodb_collection/tests/Metric.json
  entity-types/infra-mongodb_database/definition.yml
  entity-types/infra-mongodb_database/tests/Metric.json
  entity-types/infra-mongodb_instance/definition.yml
  entity-types/infra-mongodb_instance/tests/Metric.json
  entity-types/infra-redisinstance/definition.yml
  entity-types/infra-squid_cachemgr/definition.yml
  entity-types/infra-squid_cachemgr/tests/Metric.json
  relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE_AMQP.yml
  relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE_CASSANDRA.yml
  relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE_DNS.yml
  relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE_KAFKA.yml
  relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE_MYSQL.yml
  relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE_POSTGRES.yml
  relationships/synthesis/EXT-SERVICE-to-EXT-PIXIE_REDIS.yml
  relationships/synthesis/INFRA-HOST-to-EXT-SERVICE.yml
  relationships/synthesis/INFRA-HOST-to-MLOPS-MACHINE_LEARNING_MODEL.yml
  relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_AMQP.yml
  relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_CASSANDRA.yml
  relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_DNS.yml
  relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_KAFKA.yml
  relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_MYSQL.yml
  relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_POSTGRES.yml
  relationships/synthesis/INFRA-KUBERNETESCLUSTER-to-EXT-PIXIE_REDIS.yml
  relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_AMQP.yml
  relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_CASSANDRA.yml
  relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_DNS.yml
  relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_KAFKA.yml
  relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_MYSQL.yml
  relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_POSTGRES.yml
  relationships/synthesis/INFRA-KUBERNETES_POD-to-EXT-PIXIE_REDIS.yml
Labels: do-not-merge

#1215 Update to use Bridge Metrics
  entity-types/apm-application/golden_metrics.yml
Labels: freeze exception pending

#1223 feat: add destination entity definition
  entity-types/aiops-destination/definition.yml
Labels: freeze exception pending

#1245 update HOST GMs with cloud Events data
  entity-types/infra-host/golden_metrics.yml
Labels: waiting on submitter feedback
