Repository newrelic/entity-definitions, pull requests merged in 2024-07, with the labels that each got.

#1628 feat: EXT Infra Docker container to Ext service relationship synthesis
  relationships/synthesis/EXT_INFRA-DOCKER_CONTAINER-to-EXT-SERVICE.yml
Labels: waiting on submitter feedback, internal review

#1673 NR-259039-2 Adding predicate check accountID for SQS candidate file
  relationships/candidates/AWSSQSQUEUE.yml
  relationships/synthesis/EXT-SERVICE-to-INFRA-AWSSQSQUEUE.yml
Labels: do-not-merge, internal review

#1675 Cacti - New Entity Definition
  entity-types/ext-cacti/cacti_dashboard.json
  entity-types/ext-cacti/definition.yml
  entity-types/ext-cacti/golden_metrics.yml
  entity-types/ext-cacti/summary_metrics.yml
  entity-types/ext-cacti/tests/PingLatencySample.json
Labels: internal review

#1676 feat: NVIDIA Jeston entity
  entity-types/ext-nvidia_jetson/dashboard.json
  entity-types/ext-nvidia_jetson/definition.yml
  entity-types/ext-nvidia_jetson/golden_metrics.yml
  entity-types/ext-nvidia_jetson/summary_metrics.yml
  entity-types/ext-nvidia_jetson/tests/jetsonTegrastats.json
Labels: internal review
