Repository newrelic/entity-definitions, pull requests merged in 2025-01, with the labels that each got.

#1848 Add a generic rule for APM->DB relationships
  relationships/synthesis/APM-APPLICATION-to-DATABASE.yml
Labels: internal review

#1856 Add displayName as a possible tag for k8s candidate matching
  relationships/candidates/KUBERNETESCLUSTER.yml
Labels: waiting on submitter feedback

#1780 Compute ext-service OpenTelemetry golden metrics from metrics instead of spans
  entity-types/ext-service/golden_metrics.yml
Labels: draft

#1839 feat: NR 328461 add CLS browser golden signals
  entity-types/browser-application/golden_metrics.yml
  entity-types/browser-application/summary_metrics.yml
Labels: waiting on submitter feedback

#1845 feat: Adding AwsMskTopic to AwsMskBroker relationship
  relationships/candidates/AWSMSKBROKER.yml
  relationships/synthesis/INFRA-AWSMSKBROKER-to-INFRA-AWSMSKTOPIC.yml
Labels: draft
